"""GitHub integration for paper repo creation and management.

Uses GitHub App authentication (preferred) or PAT fallback.
All files committed in a single commit via the Git Trees API
to avoid triggering N workflow runs.
"""
import httpx
import base64
import datetime as _dt
import logging
from typing import Optional

from .config import get_settings
from .database import Submission
from .github_app_auth import get_github_headers

settings = get_settings()
logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"


async def create_paper_repo_from_files(submission: Submission, files: dict) -> str:
    """
    Create a new paper repository and populate it with the given files.

    Uses the Git Trees API to commit all files in a single commit,
    so only one GitHub Actions workflow run is triggered.

    files: dict of {filepath: content_string}
    Returns the repo URL.
    """
    repo_name = f"micro-{submission.slug}"
    full_name = f"{settings.github_org}/{repo_name}"

    async with httpx.AsyncClient(timeout=60.0) as client:
        headers = await get_github_headers()

        # Create repository (or confirm it exists)
        resp = await client.post(
            f"{GITHUB_API}/orgs/{settings.github_org}/repos",
            headers=headers,
            json={
                "name": repo_name,
                "description": f"OMC Paper: {submission.title}",
                "private": False,
                "auto_init": True,
                "has_issues": True,
                "has_projects": False,
                "has_wiki": False,
            },
        )

        if resp.status_code == 201:
            logger.info(f"Created repo {full_name}")
        elif resp.status_code == 422:
            logger.info(f"Repo {full_name} already exists")
        else:
            raise RuntimeError(f"Failed to create repo: {resp.status_code} {resp.text}")

        # Get the current HEAD commit SHA and tree SHA
        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{full_name}/git/ref/heads/main",
            headers=headers,
        )
        if ref_resp.status_code != 200:
            raise RuntimeError(f"Failed to get ref: {ref_resp.status_code} {ref_resp.text}")
        base_commit_sha = ref_resp.json()["object"]["sha"]

        commit_resp = await client.get(
            f"{GITHUB_API}/repos/{full_name}/git/commits/{base_commit_sha}",
            headers=headers,
        )
        base_tree_sha = commit_resp.json()["tree"]["sha"]

        # Create blobs for all files
        tree_items = []
        for filepath, content in files.items():
            blob_resp = await client.post(
                f"{GITHUB_API}/repos/{full_name}/git/blobs",
                headers=headers,
                json={
                    "content": content,
                    "encoding": "utf-8",
                },
            )
            if blob_resp.status_code != 201:
                logger.warning(f"Failed to create blob for {filepath}: {blob_resp.status_code}")
                continue
            tree_items.append({
                "path": filepath,
                "mode": "100644",
                "type": "blob",
                "sha": blob_resp.json()["sha"],
            })

        # Create a new tree with all files
        tree_resp = await client.post(
            f"{GITHUB_API}/repos/{full_name}/git/trees",
            headers=headers,
            json={
                "base_tree": base_tree_sha,
                "tree": tree_items,
            },
        )
        if tree_resp.status_code != 201:
            raise RuntimeError(f"Failed to create tree: {tree_resp.status_code} {tree_resp.text}")
        new_tree_sha = tree_resp.json()["sha"]

        # Create a single commit
        commit_resp = await client.post(
            f"{GITHUB_API}/repos/{full_name}/git/commits",
            headers=headers,
            json={
                "message": f"Add manuscript ({len(files)} files)\n\nGenerated by OMC Platform",
                "tree": new_tree_sha,
                "parents": [base_commit_sha],
            },
        )
        if commit_resp.status_code != 201:
            raise RuntimeError(f"Failed to create commit: {commit_resp.status_code} {commit_resp.text}")
        new_commit_sha = commit_resp.json()["sha"]

        # Update the ref to point to the new commit
        ref_update = await client.patch(
            f"{GITHUB_API}/repos/{full_name}/git/refs/heads/main",
            headers=headers,
            json={"sha": new_commit_sha},
        )
        if ref_update.status_code != 200:
            raise RuntimeError(f"Failed to update ref: {ref_update.status_code} {ref_update.text}")

        # Enable GitHub Pages so the rendered manuscript is actually viewable.
        await ensure_pages(full_name, client=client, headers=headers,
                           base_commit_sha=new_commit_sha)

        repo_url = f"https://github.com/{full_name}"
        logger.info(f"Published {len(files)} files to {full_name} in one commit")
        return repo_url


async def ensure_pages(
    repo_full_name: str,
    client: httpx.AsyncClient | None = None,
    headers: dict | None = None,
    base_commit_sha: str | None = None,
) -> str | None:
    """Enable GitHub Pages for a paper repo and return its public URL.

    Idempotent, so it doubles as a backfill for repos created before this
    existed. The manuscript workflow (peaceiris/actions-gh-pages) publishes
    ./docs to the `gh-pages` branch, but that branch doesn't exist until the
    first render — and the Pages API refuses a source branch that isn't there.
    Previously the call was fired blind with its status ignored, so Pages was
    simply never enabled and the paper was unviewable. Seed an empty gh-pages
    branch first, then enable Pages against it; the workflow force-pushes real
    content over it later.
    """
    own_client = client is None
    if own_client:
        client = httpx.AsyncClient(timeout=30.0)
    if headers is None:
        headers = await get_github_headers()
    try:
        # Already enabled? Then we're done.
        existing = await client.get(f"{GITHUB_API}/repos/{repo_full_name}/pages", headers=headers)
        if existing.status_code == 200:
            return existing.json().get("html_url")

        # Seed gh-pages if the render workflow hasn't created it yet.
        gh_ref = await client.get(
            f"{GITHUB_API}/repos/{repo_full_name}/git/ref/heads/gh-pages", headers=headers
        )
        if gh_ref.status_code != 200:
            sha = base_commit_sha
            if not sha:
                repo = await client.get(f"{GITHUB_API}/repos/{repo_full_name}", headers=headers)
                default_branch = repo.json().get("default_branch", "main")
                head = await client.get(
                    f"{GITHUB_API}/repos/{repo_full_name}/git/ref/heads/{default_branch}",
                    headers=headers,
                )
                sha = head.json()["object"]["sha"]
            seed = await client.post(
                f"{GITHUB_API}/repos/{repo_full_name}/git/refs",
                headers=headers,
                json={"ref": "refs/heads/gh-pages", "sha": sha},
            )
            if seed.status_code not in (201, 422):  # 422 = already exists
                logger.warning(
                    "Could not seed gh-pages for %s: %s %s",
                    repo_full_name, seed.status_code, seed.text[:200],
                )
                return None

        resp = await client.post(
            f"{GITHUB_API}/repos/{repo_full_name}/pages",
            headers=headers,
            json={"source": {"branch": "gh-pages", "path": "/"}},
        )
        if resp.status_code in (201, 204):
            url = resp.json().get("html_url") if resp.content else None
            logger.info("Enabled GitHub Pages for %s (%s)", repo_full_name, url)
            return url
        if resp.status_code == 409:  # already enabled
            return None
        logger.warning(
            "Failed to enable Pages for %s: %s %s",
            repo_full_name, resp.status_code, resp.text[:200],
        )
        return None
    finally:
        if own_client:
            await client.aclose()


async def create_review_pr(
    repo_full_name: str,
    review_comments: list[dict],
    review_type: str,
) -> str:
    """
    Create a review PR with AI-generated comments.

    review_comments: list of {"body": "comment markdown"}
    Returns the PR URL.
    """
    async with httpx.AsyncClient(timeout=30.0) as client:
        headers = await get_github_headers()

        # Get default branch SHA
        repo_resp = await client.get(
            f"{GITHUB_API}/repos/{repo_full_name}",
            headers=headers,
        )
        default_branch = repo_resp.json()["default_branch"]

        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{repo_full_name}/git/ref/heads/{default_branch}",
            headers=headers,
        )
        base_sha = ref_resp.json()["object"]["sha"]

        # Create review branch with timestamp to avoid conflicts on re-run
        import time as _time
        stamp = int(_time.time())
        branch_name = f"review/{review_type}-{stamp}"

        await client.post(
            f"{GITHUB_API}/repos/{repo_full_name}/git/refs",
            headers=headers,
            json={
                "ref": f"refs/heads/{branch_name}",
                "sha": base_sha,
            },
        )

        # Commit the review to the branch BEFORE opening the PR. A branch created
        # at the base SHA is identical to the default branch, and GitHub rejects
        # such a PR with 422 "No commits between main and review/..." — which
        # silently broke every AI review. Writing the review under .omc/ also
        # keeps it in the provenance trail rather than only in PR comments.
        review_md = "\n\n---\n\n".join(
            c.get("body", "") for c in review_comments if c.get("body")
        ) or f"_No {review_type} findings were reported._"
        review_doc = (
            f"# AI Review: {review_type}\n\n"
            f"Generated by the OMC platform at "
            f"{_dt.datetime.now(_dt.timezone.utc).strftime('%Y-%m-%d %H:%M:%SZ')}.\n\n"
            f"{review_md}\n"
        )
        file_resp = await client.put(
            f"{GITHUB_API}/repos/{repo_full_name}/contents/.omc/reviews/{review_type}-{stamp}.md",
            headers=headers,
            json={
                "message": f"AI review: {review_type}\n\nGenerated by OMC Platform",
                "content": base64.b64encode(review_doc.encode()).decode(),
                "branch": branch_name,
            },
        )
        if file_resp.status_code not in (200, 201):
            raise RuntimeError(
                f"Failed to commit review file: {file_resp.status_code} {file_resp.text}"
            )

        # Create PR
        pr_resp = await client.post(
            f"{GITHUB_API}/repos/{repo_full_name}/pulls",
            headers=headers,
            json={
                "title": f"AI Review: {review_type}",
                "body": f"Automated {review_type} review by the OMC platform.",
                "head": branch_name,
                "base": default_branch,
            },
        )

        if pr_resp.status_code != 201:
            raise RuntimeError(f"Failed to create PR: {pr_resp.text}")

        pr_data = pr_resp.json()
        pr_number = pr_data["number"]

        # Add review comments to the PR
        for comment in review_comments:
            await client.post(
                f"{GITHUB_API}/repos/{repo_full_name}/issues/{pr_number}/comments",
                headers=headers,
                json={"body": comment["body"]},
            )

        return pr_data["html_url"]
