"""GitHub integration for paper repo creation and management.

Uses GitHub App authentication (preferred) or PAT fallback.
All files committed in a single commit via the Git Trees API
to avoid triggering N workflow runs.
"""
import httpx
import base64
import logging
from typing import Optional

from .config import get_settings
from .database import Submission
from .github_app_auth import get_github_headers

settings = get_settings()
logger = logging.getLogger(__name__)

GITHUB_API = "https://api.github.com"


async def create_paper_repo_from_files(submission: Submission, files: dict) -> str:
    """
    Create a new paper repository and populate it with the given files.

    Uses the Git Trees API to commit all files in a single commit,
    so only one GitHub Actions workflow run is triggered.

    files: dict of {filepath: content_string}
    Returns the repo URL.
    """
    repo_name = f"micro-{submission.slug}"
    full_name = f"{settings.github_org}/{repo_name}"

    async with httpx.AsyncClient(timeout=60.0) as client:
        headers = await get_github_headers()

        # Create repository (or confirm it exists)
        resp = await client.post(
            f"{GITHUB_API}/orgs/{settings.github_org}/repos",
            headers=headers,
            json={
                "name": repo_name,
                "description": f"OMC Paper: {submission.title}",
                "private": False,
                "auto_init": True,
                "has_issues": True,
                "has_projects": False,
                "has_wiki": False,
            },
        )

        if resp.status_code == 201:
            logger.info(f"Created repo {full_name}")
        elif resp.status_code == 422:
            logger.info(f"Repo {full_name} already exists")
        else:
            raise RuntimeError(f"Failed to create repo: {resp.status_code} {resp.text}")

        # Get the current HEAD commit SHA and tree SHA
        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{full_name}/git/ref/heads/main",
            headers=headers,
        )
        if ref_resp.status_code != 200:
            raise RuntimeError(f"Failed to get ref: {ref_resp.status_code} {ref_resp.text}")
        base_commit_sha = ref_resp.json()["object"]["sha"]

        commit_resp = await client.get(
            f"{GITHUB_API}/repos/{full_name}/git/commits/{base_commit_sha}",
            headers=headers,
        )
        base_tree_sha = commit_resp.json()["tree"]["sha"]

        # Create blobs for all files
        tree_items = []
        for filepath, content in files.items():
            blob_resp = await client.post(
                f"{GITHUB_API}/repos/{full_name}/git/blobs",
                headers=headers,
                json={
                    "content": content,
                    "encoding": "utf-8",
                },
            )
            if blob_resp.status_code != 201:
                logger.warning(f"Failed to create blob for {filepath}: {blob_resp.status_code}")
                continue
            tree_items.append({
                "path": filepath,
                "mode": "100644",
                "type": "blob",
                "sha": blob_resp.json()["sha"],
            })

        # Create a new tree with all files
        tree_resp = await client.post(
            f"{GITHUB_API}/repos/{full_name}/git/trees",
            headers=headers,
            json={
                "base_tree": base_tree_sha,
                "tree": tree_items,
            },
        )
        if tree_resp.status_code != 201:
            raise RuntimeError(f"Failed to create tree: {tree_resp.status_code} {tree_resp.text}")
        new_tree_sha = tree_resp.json()["sha"]

        # Create a single commit
        commit_resp = await client.post(
            f"{GITHUB_API}/repos/{full_name}/git/commits",
            headers=headers,
            json={
                "message": f"Add manuscript ({len(files)} files)\n\nGenerated by OMC Platform",
                "tree": new_tree_sha,
                "parents": [base_commit_sha],
            },
        )
        if commit_resp.status_code != 201:
            raise RuntimeError(f"Failed to create commit: {commit_resp.status_code} {commit_resp.text}")
        new_commit_sha = commit_resp.json()["sha"]

        # Update the ref to point to the new commit
        ref_update = await client.patch(
            f"{GITHUB_API}/repos/{full_name}/git/refs/heads/main",
            headers=headers,
            json={"sha": new_commit_sha},
        )
        if ref_update.status_code != 200:
            raise RuntimeError(f"Failed to update ref: {ref_update.status_code} {ref_update.text}")

        # Enable GitHub Pages on the repo
        await client.post(
            f"{GITHUB_API}/repos/{full_name}/pages",
            headers=headers,
            json={"source": {"branch": "gh-pages", "path": "/"}},
        )

        repo_url = f"https://github.com/{full_name}"
        logger.info(f"Published {len(files)} files to {full_name} in one commit")
        return repo_url


async def create_review_pr(
    repo_full_name: str,
    review_comments: list[dict],
    review_type: str,
) -> str:
    """
    Create a review PR with AI-generated comments.

    review_comments: list of {"body": "comment markdown"}
    Returns the PR URL.
    """
    async with httpx.AsyncClient(timeout=30.0) as client:
        headers = await get_github_headers()

        # Get default branch SHA
        repo_resp = await client.get(
            f"{GITHUB_API}/repos/{repo_full_name}",
            headers=headers,
        )
        default_branch = repo_resp.json()["default_branch"]

        ref_resp = await client.get(
            f"{GITHUB_API}/repos/{repo_full_name}/git/ref/heads/{default_branch}",
            headers=headers,
        )
        base_sha = ref_resp.json()["object"]["sha"]

        # Create review branch with timestamp to avoid conflicts on re-run
        import time as _time
        branch_name = f"review/{review_type}-{int(_time.time())}"

        await client.post(
            f"{GITHUB_API}/repos/{repo_full_name}/git/refs",
            headers=headers,
            json={
                "ref": f"refs/heads/{branch_name}",
                "sha": base_sha,
            },
        )

        # Create PR
        pr_resp = await client.post(
            f"{GITHUB_API}/repos/{repo_full_name}/pulls",
            headers=headers,
            json={
                "title": f"AI Review: {review_type}",
                "body": f"Automated {review_type} review by the OMC platform.",
                "head": branch_name,
                "base": default_branch,
            },
        )

        if pr_resp.status_code != 201:
            raise RuntimeError(f"Failed to create PR: {pr_resp.text}")

        pr_data = pr_resp.json()
        pr_number = pr_data["number"]

        # Add review comments to the PR
        for comment in review_comments:
            await client.post(
                f"{GITHUB_API}/repos/{repo_full_name}/issues/{pr_number}/comments",
                headers=headers,
                json={"body": comment["body"]},
            )

        return pr_data["html_url"]
