"""Post-pipeline processing: create paper repo from pipeline outputs."""
import json
import logging
from pathlib import Path
from string import Template
from datetime import datetime

from .config import get_settings
from .database import Submission

settings = get_settings()
logger = logging.getLogger(__name__)

# Path to paper-repo template
TEMPLATE_DIR = Path(__file__).parent.parent.parent / "templates" / "paper-repo"


def render_manuscript_template(
    submission: Submission,
    sections: dict,
    author_name: str = "",
    affiliation: str = "",
) -> str:
    """
    Render the manuscript.qmd template with generated content.

    sections should have keys: introduction, methods, results, discussion, abstract
    """
    template_path = TEMPLATE_DIR / "manuscript.qmd"
    template_text = template_path.read_text()

    metadata = submission.sample_metadata or {}

    # Build substitution dict
    subs = {
        "title": submission.title or f"Analysis of {submission.sra_accession}",
        "author_name": author_name or "OMC Contributors",
        "affiliation": affiliation or "",
        "date": datetime.utcnow().strftime("%Y-%m-%d"),
        "abstract": sections.get("abstract", "*Abstract pending.*"),
        "sra_accession": submission.sra_accession,
        "pipeline": submission.pipeline.value,
        "paper_id": f"paper-{submission.id:04d}",
        "introduction": sections.get("introduction", "*Introduction pending.*"),
        "methods_detail": sections.get("methods", ""),
        "results": sections.get("results", "*Results pending.*"),
        "discussion": sections.get("discussion", "*Discussion pending.*"),
    }

    # Use simple {{key}} replacement (not Python's Template which uses $)
    rendered = template_text
    for key, value in subs.items():
        rendered = rendered.replace(f"{{{{{key}}}}}", str(value))

    return rendered


def build_paper_repo_files(
    submission: Submission,
    sections: dict,
    figures_json: dict | None = None,
    tables: dict | None = None,
    bibtex: str = "",
    author_name: str = "",
    affiliation: str = "",
) -> dict:
    """
    Build all files needed for the paper repository.

    Returns a dict of {filepath: content} ready to commit to GitHub.
    """
    files = {}

    # manuscript.qmd (the main document)
    files["manuscript.qmd"] = render_manuscript_template(
        submission, sections, author_name, affiliation,
    )

    # _quarto.yml
    files["_quarto.yml"] = (TEMPLATE_DIR / "_quarto.yml").read_text()

    # styles.css
    files["styles.css"] = (TEMPLATE_DIR / "styles.css").read_text()

    # references.bib
    files["references.bib"] = bibtex or (TEMPLATE_DIR / "references.bib").read_text()

    # GitHub Actions workflow
    files[".github/workflows/render.yml"] = (
        TEMPLATE_DIR / ".github" / "workflows" / "render.yml"
    ).read_text()

    # data/accessions.yaml
    import yaml
    accession_data = {
        "sra_accession": submission.sra_accession,
        "pipeline": submission.pipeline.value,
        "submitted_at": submission.submitted_at.isoformat() if submission.submitted_at else None,
    }
    files["data/accessions.yaml"] = yaml.dump(accession_data)

    # data/sra_metadata.json (full metadata from NCBI)
    if submission.sample_metadata:
        files["data/sra_metadata.json"] = json.dumps(
            submission.sample_metadata, indent=2, default=str
        )

    # paper.yaml (JSON-LD metadata)
    paper_meta = {
        "@context": "https://schema.org",
        "@type": "ScholarlyArticle",
        "name": submission.title,
        "author": [{"@type": "Person", "name": author_name}] if author_name else [],
        "dateCreated": datetime.utcnow().isoformat(),
        "license": "https://creativecommons.org/licenses/by/4.0/",
        "url": f"https://papers.opencommunity.science/paper-{submission.id:04d}",
    }
    files["paper.yaml"] = yaml.dump(paper_meta)

    # Interactive figures (Plotly JSON)
    if figures_json:
        for name, fig_data in figures_json.items():
            files[f"results/figures/{name}.json"] = json.dumps(fig_data, default=str)

    # Tables
    if tables:
        for name, table_content in tables.items():
            files[f"results/tables/{name}"] = table_content

    # LICENSE
    files["LICENSE"] = (TEMPLATE_DIR / "LICENSE").read_text()

    # CONTRIBUTORS.md
    files["CONTRIBUTORS.md"] = f"""# Contributors

*Auto-generated from git history.*

## Authors

- {author_name or 'OMC Contributors'}

## AI Assistance

Manuscript draft generated by the [Open Microbial Community](https://opencommunity.science) platform using Claude.
"""

    return files


async def process_completed_submission(submission: Submission, db_session) -> str:
    """
    Full post-pipeline processing:
    1. (Future) Parse pipeline outputs from HPC
    2. Generate manuscript via AI
    3. Create GitHub repo with all files
    4. Return repo URL

    For now, creates repo with template content.
    """
    from .github_integration import create_paper_repo_from_files
    from .database import SubmissionStatus

    try:
        # Step 1: Parse pipeline outputs (TODO: implement)
        # For now, use empty placeholders
        figures_json = {}
        tables = {}
        pipeline_outputs = {}

        # Step 2: Generate manuscript sections via AI (if API key available)
        sections = {}
        if settings.anthropic_api_key:
            from ai.manuscript_generator import generate_manuscript_draft
            sections = await generate_manuscript_draft(
                api_key=settings.anthropic_api_key,
                pipeline_outputs=pipeline_outputs,
                interview_data=submission.interview_data or {},
                pipeline_type=submission.pipeline.value,
                sra_accession=submission.sra_accession,
            )
        else:
            # Placeholder sections
            sections = {
                "abstract": "*Abstract will be generated after pipeline outputs and author interview are available.*",
                "introduction": "*Introduction pending AI generation.*",
                "methods": "",
                "results": "*Results will be populated from pipeline outputs.*",
                "discussion": "*Discussion pending AI generation.*",
            }

        # Step 3: Build repo files
        repo_files = build_paper_repo_files(
            submission=submission,
            sections=sections,
            figures_json=figures_json,
            tables=tables,
        )

        # Step 4: Create GitHub repo
        repo_url = await create_paper_repo_from_files(submission, repo_files)

        # Update submission
        submission.github_repo = repo_url
        submission.status = SubmissionStatus.DRAFTING
        await db_session.commit()

        logger.info(f"Created paper repo for submission {submission.id}: {repo_url}")
        return repo_url

    except Exception as e:
        logger.error(f"Failed to process submission {submission.id}: {e}")
        submission.status = SubmissionStatus.FAILED
        submission.error_message = f"Post-processing failed: {str(e)}"
        await db_session.commit()
        raise
