# Add to the server block in /etc/nginx/sites-available/omc
# (microbial.opencommunity.science)

location /relay/ {
    proxy_pass http://127.0.0.1:8484/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
